# Generated by Django 5.0.7 on 2026-08-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eno", models.IntegerField()),
                ("ename", models.CharField(max_length=100)),
                ("esal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("eaddr", models.CharField(max_length=255)),
            ],
        ),
    ]
